package ru.valera.bot.to;

public enum MessageType {
    DEFAULT, NOTIFY, CUSTOM,

    START, END, HELP,

    GREETING, VALERA, MINING, CALLBACK_MINING, GIRLS, NEW_USER,
    CURRENCY, WEATHER, CALLBACK_WEATHER,
    STICKER,

    TITS_GIF, TITS_VIDEO, GIRLS_VIDEO,

    STATUSES_VK, ANECDOTE,

    TEXT_CONTAIN_EMOJI
}
